### ISSUE TITLE
The icon and fan art images do not load

### ISSUE THREAD

**Issue by lubo** [lubo/KODI-Popcorn-Time#1]
This has been a problem since 36678dbd1c31179c4c7ffc95aadc92a4f81f183f.

**Comment by ruipisco** [comment]
Hi lubo! To fix the icon of the addon just edit the addon.xml file and at the end of the section `<extension>` add this lines to the section:
`<assets>
          <icon>icon.png</icon>
          <fanart>fanart.jpg</fanart>
</assets>`

**Comment by lubo** [comment]
Hi @ruipisco. I tried that and it didn't work. Please, send a PR if you got it to work.

**Comment by ruipisco** [comment]
hi @lubo . In the root of the folder plugin.video.kodipopcorntime you will need to have the icon.png and fanart.jpg, that i leave in attach for you to replace in the folder and then test it!

The in the same root folder you will have the addon.xml file that you will need to edit, delete all the content and then paste this lines:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="plugin.video.kodipopcorntime" name="KODI Popcorn Time" version="1.7.6" provider-name="lubo">
    <requires>
        <import addon="xbmc.python" version="3.0.0" />
    </requires>
    <extension point="xbmc.python.pluginsource" library="addon.py">
        <provides>video</provides>
    </extension>
    <extension point="xbmc.addon.metadata">
        <reuselanguageinvoker>false</reuselanguageinvoker>
        <platform>all</platform>
        <website>https://github.com/lubo/KODI-Popcorn-Time</website>
        <forum>https://github.com/lubo/KODI-Popcorn-Time/issues</forum>
        <source>https://github.com/lubo/KODI-Popcorn-Time</source>
        <license>GNU GENERAL PUBLIC LICENSE. Version 3, 29 June 2007</license>
        <summary lang="de_DE">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="en_GB">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="es_ES">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="fr_FR">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="hr_HR">Trenutačno gledajte filmove, TV Serije i Anime.</summary>
        <summary lang="zh_CN">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="nl_NL">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="pl_PL">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="pt_PT">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="pt_BR">Immediately stream movies, TV Shows and Animes.</summary>
        <summary lang="sl_SI">Takojšnji ogled Filmov, TV Serij ter Anime.</summary>
        <description lang="de_DE">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="en_GB">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="es_ES">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="fr_FR">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="hr_HR">Sa KODI Popcorn Time možete pretraživati filmove, TV serije i Anime koje možete odmah gledati u KODIJU. NAPOMENA: KODI Popcorn Time će nastaviti dijeliti sadržaj dok gledate film, TV seriju ili Anime.</description>
        <description lang="zh_CN">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="nl_NL">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="pl_PL">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="pt_PT">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="pt_BR">With KODI Popcorn Time you can search for movies, TV shows and Animes that you can see immediately in KODI. NOTE: KODI Popcorn Time will continue sharing content while watching a movie TV show or Anime.</description>
        <description lang="sl_SI">Z KODI Popcorn Time lahko iščete Filme, TV Serije in Anime, ki si jih lahko takoj ogledaš v KODI-ju. OPOMBA: KODI Popcorn Time med ogledom filmov, TV Serij ter Anime deli video dalje tudi drugim uporabnikom.</description>
        <assets>
          <icon>icon.png</icon>
          <fanart>fanart.jpg</fanart>
        </assets>
    </extension>
</addon>`

[fanart](https://user-images.githubusercontent.com/32041748/144058893-0437c584-594b-4b33-81ab-6866fde3f9f8.jpg)

[icon](https://user-images.githubusercontent.com/32041748/144058951-c6fff975-19cc-4a32-a98c-98c6bad9d290.png)

.
